apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: prometheus
    version: 25.0.0 # Version of Helm Chart
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus
    namespace: monitoring
    valuesFile: values.yaml
