apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/app

patches:
  - path: service-dev.yaml
  - path: patches/app-patches/deployment-patch.yaml

commonLabels:
  environment: dev
