apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/grafana/

#patchesStrategicMerge:
#patches:
 # - deployment-patch.yaml
patches:
  - target:
      kind: Deployment
      name: grafana
    path: deployment-patch.yaml
transformers:
  - annotations-transformer.yaml

commonLabels:
  environment: prod