kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: project-2
  namespace: default
spec:
  sourceNamespaces:
  - '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'