apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: default
  labels:
    app: "true"
spec:
  replicas: 2 
  template:
    spec:
      containers:
        - name: nginx
          resources:
            limits:
              cpu: "550m" 
              memory: "256Mi" 
            requests:
              cpu: "200m" 
              memory: "246Mi"
