apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: default
  labels:
    app: "true"
spec:
  replicas: 2 # Update the replica count to 3
  template:
    spec:
      containers:
        - name: nginx
          resources:
            limits:
              cpu: "550m" # Lower CPU limit to 200m (0.2 CPU cores)
              memory: "256Mi" # Lower memory limit to 256 MiB
            requests:
              cpu: "200m" # Lower CPU request to 100m (0.1 CPU cores)
              memory: "246Mi"